### ISSUE TITLE
Search Results View

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-webapp#13]
Mockup the Search Results.  Feel free to experiment visually (e.g text vs. graphical).

**Comment by herrjosua** [comment]
### Search Results
![search results alt](https://cloud.githubusercontent.com/assets/1341786/15966836/d109c20e-2ef2-11e6-9183-35cf5d7f0e67.png)

**Comment by camelspeed** [comment]
initial layout shows promise. We need to explore what other info is most relevant so the user can make quick glances to determine if the result is relevant or interesting.

**Comment by camelspeed** [comment]
Issue moved to [Project-Heimdall/heimdall-uiapp #12](https://github.com/Project-Heimdall/heimdall-uiapp/issues/12) via [**ZenHub**](https://www.zenhub.com/)
