### ISSUE TITLE
User Research - first round

### ISSUE THREAD

**Issue by herrjosua** [Project-Heimdall/heimdall-webapp#52]
Perform user interviews for STAGE using the following script as a base:

[User_Interview.docx](https://github.com/Project-Heimdall/heimdall-webapp/files/314690/User_Interview.docx)

**Comment by camelspeed** [comment]
Issue moved to [Project-Heimdall/heimdall-uiapp #8](https://github.com/Project-Heimdall/heimdall-uiapp/issues/8) via [**ZenHub**](https://www.zenhub.com/)
