### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by herrjosua** [Project-Heimdall/heimdall-webapp#53]
Story to remove empty directories, and remove the static HTML files from the heimdall-webapp directory

**Comment by camelspeed** [comment]
Also please remove files that are unused or *old*.  I've noticed a couple of HTML files with the suffice `_old` in the code base. @natesol-code21 @herrjosua

**Comment by camelspeed** [comment]
out of date since we've done some clean up and continue to do so with under other issues.
