### ISSUE TITLE
Implement the ranking algorithm service on the API Service

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-webapp#77]

**Comment by onetrickwolf** [comment]
heimdall-search#14 

Ranking may be handled by ES

**Comment by camelspeed** [comment]
Issue moved to [Project-Heimdall/heimdall-search #17](https://github.com/Project-Heimdall/heimdall-search/issues/17) via [**ZenHub**](https://www.zenhub.com/)
